/* Step 1: Clear existing product info
Delete Category
Delete MENUITEM
DElete TOptions
DElete TOptionsTemp
Delete InstructionLinkGroup
delete InstructionLink
delete CATEGORYMENUITEM
delete MENUGROUPLINKCATEGORY
*/

/* Step 2:  Convert TCAT ---> Category */

INSERT INTO [MainDB].[dbo].[Category] (BUTTONCOLOR,CODE,SHOWONMAINMENU,SHOWONPOSMENU,CATEGORY,CATEGORY1,ONLINEDISPLAYNAME1,ONLINEDISPLAYNAME2,FONTSIZE,
FONTBOLD,FONTITALIC,FONTUNDERLINE,FONTSTRIKEOUT,ORDERINDEX,SHOWONDINEINMENU,SHOWONTAKEAWAYMENU,SHOWONQUICKSALEMENU,SHOWONDELIVERYMENU,SHOWONPICKUPMENU,MINIMUMCHOICEQTY,
MAXIMUMCHOICEQTY,ONLINESTATUS,QRCODESTATUS,Enable)
SELECT F_COLOR,RIGHT(F_CATCODE,3) ,ISNULL(F_SHOWINPANEL,1),ISNULL(F_SHOWINPANEL,1),F_CATDESC,F_CATDESC,F_CATDESC,F_CATDESC,0,0,0,0,0,0,1,1,1,1,1,0,0,1,1,1
FROM [ILDDB].[DBO].[TCAT]

/* Step 3: Add Instructions --*/
/* Need do it manually, the category will use in some of following cmd, eg. 18*/

/* Step 4: Convert TProduct ---> MenuItem */

INSERT [MainDB].[DBO].[MENUITEM] (ITEMCODE,BARCODE,DESCRIPTION1,DESCRIPTION2,PRICE,TAXRATE,CATEGORY,ACTIVE, ITEMGROUP,BUTTONCOLOR,FONTCOLOR,
INSTRUCTION,MULTIPLE,PRICE1,PRICE2,PRICE3,PRINTERPORT,FONTSIZE,FONTBOLD,FONTITALIC,FONTUNDERLINE,FONTSTRIKEOUT,ALLOWDISCOUNT,JOBLISTCOLOR,OPENPRICE,PRINTERPORT1,
PRINTERPORT2,HAPPYHOURPRICE1,HAPPYHOURPRICE2,HAPPYHOURPRICE3,HAPPYHOURPRICE4,DEFAULTQTY,SUBDESCRIPTIONSWAP,MAINPOSITION,POSPOSITION,KITCHENSCREENFONTCOLOR,
PRINTERPORT3,ONLYSHOWONSUBMENU,BUTTONCOLOR1,FONTCOLOR1,FONTSIZE1,FONTBOLD1,FONTITALIC1,FONTUNDERLINE1,FONTSTRIKEOUT1,PHONEORDERPOSITION,AUTOPOPSPELLINSTRUCTIONKEYBOARD,
KITCHENSCREEN1,KITCHENSCREEN2,KITCHENSCREEN3,KITCHENSCREEN4,SCALABLE,WEEKENDPRICE,WEEKENDPRICE1,WEEKENDPRICE2,WEEKENDPRICE3,TIMECHARGEITEM,SOLDOUT,PROMOTIONITEM,
CANBEREDEEMITEM,TAREWEIGHT,COST,COST1,COST2,COST3,QUANTITYFOLLOWBYPEOPLECOUNT,REDEEMPOINTS,ONLINEORDERITEM,OTHERCHARGEITEM,WEIGHTDIVIDEMEASUREASQTY,MEASUREWEIGHT,
PACKAGEPRICE,PACKAGEPRICE1,PACKAGEPRICE2,PACKAGEPRICE3,SUBCATEGORY,MAXIMUMQTY,TIMECONSUMINGITEM,ONLINESTATUS,QRCODESTATUS,ONLINEPRICE1,ONLINEPRICE2,ONLINEPRICE3,
STOCKCONTROL,STOCKQTY,DVERSION)
SELECT LEFT(F_ITEMNO,1) + RIGHT(F_ITEMNO,3) ,F_ITEMNO,F_DESC,F_DESCKITCHEN,F_PRICE,10,RIGHT(F_CATCODE,3),1,'FOOD',0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,
0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM [ILDDB].[DBO].[TPRODUCT]

/* Step 5: CREATE TEMP TABLE ON ZII DB */
CREATE TABLE [dbo].[TOptionsTemp](
	[F_Code] [int] IDENTITY(1,1) NOT NULL,
	[F_Desc] [nvarchar](100) NULL,
	[F_Price] [money] NULL
) ON [PRIMARY]
GO

/* Step 6: COPY TOPTIONS TO ZII DB */

insert into [MainDB].[dbo].[TOptionsTemp] ([F_Desc],[F_Price])  
SELECT distinct F_Desc,F_ExtraPrice FROM [ILDDB].[dbo].[TOPTIONS]

/* Step 7: CONVERT TEMP TABLE TO MENUITEM */

INSERT [MainDB].[DBO].[MENUITEM] (ITEMCODE,BARCODE,DESCRIPTION1,DESCRIPTION2,PRICE,TAXRATE,CATEGORY,ACTIVE, ITEMGROUP,BUTTONCOLOR,FONTCOLOR,
INSTRUCTION,MULTIPLE,PRICE1,PRICE2,PRICE3,PRINTERPORT,FONTSIZE,FONTBOLD,FONTITALIC,FONTUNDERLINE,FONTSTRIKEOUT,ALLOWDISCOUNT,JOBLISTCOLOR,OPENPRICE,PRINTERPORT1,
PRINTERPORT2,HAPPYHOURPRICE1,HAPPYHOURPRICE2,HAPPYHOURPRICE3,HAPPYHOURPRICE4,DEFAULTQTY,SUBDESCRIPTIONSWAP,MAINPOSITION,POSPOSITION,KITCHENSCREENFONTCOLOR,
PRINTERPORT3,ONLYSHOWONSUBMENU,BUTTONCOLOR1,FONTCOLOR1,FONTSIZE1,FONTBOLD1,FONTITALIC1,FONTUNDERLINE1,FONTSTRIKEOUT1,PHONEORDERPOSITION,AUTOPOPSPELLINSTRUCTIONKEYBOARD,
KITCHENSCREEN1,KITCHENSCREEN2,KITCHENSCREEN3,KITCHENSCREEN4,SCALABLE,WEEKENDPRICE,WEEKENDPRICE1,WEEKENDPRICE2,WEEKENDPRICE3,TIMECHARGEITEM,SOLDOUT,PROMOTIONITEM,
CANBEREDEEMITEM,TAREWEIGHT,COST,COST1,COST2,COST3,QUANTITYFOLLOWBYPEOPLECOUNT,REDEEMPOINTS,ONLINEORDERITEM,OTHERCHARGEITEM,WEIGHTDIVIDEMEASUREASQTY,MEASUREWEIGHT,
PACKAGEPRICE,PACKAGEPRICE1,PACKAGEPRICE2,PACKAGEPRICE3,SUBCATEGORY,MAXIMUMQTY,TIMECONSUMINGITEM,ONLINESTATUS,QRCODESTATUS,ONLINEPRICE1,ONLINEPRICE2,ONLINEPRICE3,
STOCKCONTROL,STOCKQTY,DVERSION)
SELECT case when F_Code < 1000 then '_' + convert(nvarchar,F_Code) else 'X' + right(convert(nvarchar,F_Code),3) end ,F_Code,F_DESC,'' ,F_PRICE,10,'',1,'FOOD',0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,
0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM [MainDB].[DBO].[ToptionsTemp]

/* Step 8:Set Options to Instruction Category*/
Update MenuItem set Category = '18' where Instruction = 1

/* Step 9:Import Toptions, run the command below*/

/* Step 10: CREATE TEMP TABLE ON ZII DB*/
CREATE TABLE [dbo].[TOptions](
	[F_CODE] [nvarchar](30) NULL,
	[F_Desc] [nvarchar](30) NULL,
	[F_Desc2] [nvarchar](30) NULL,
	[F_ItemNo] [nvarchar](20) NULL,
	[F_OptionType] [int] NULL,
	[F_ExtraPrice] [money] NULL,
	[F_Order] [int] NULL,
	[F_NotForSelfOrder] [int] NULL,
	[F_IsKeyOption] [int] NULL,
	[F_WebSync] [int] NULL,
) ON [PRIMARY]

GO

insert into [MainDB].[dbo].[TOptions] (
      [F_CODE]
      ,[F_Desc]
      ,[F_Desc2]
      ,[F_ItemNo]
      ,[F_OptionType]
      ,[F_ExtraPrice]
      ,[F_Order]
      ,[F_NotForSelfOrder]
      ,[F_IsKeyOption]
)  
SELECT [F_CODE]
      ,[F_Desc]
      ,[F_Desc2]
      ,[F_ItemNo]
      ,[F_OptionType]
      ,[F_ExtraPrice]
      ,[F_Order]
      ,[F_NotForSelfOrder]
      ,[F_IsKeyOption]
 FROM [ILDDB].[dbo].[TOPTIONS]

/* Step 11: Reset Code for options */
update [MainDB].[DBO].[Toptions] set F_Code =
(select ItemCode From MenuItem where MenuItem.Description1 = TOptions.F_Desc
and MenuItem.Price = TOptions.F_ExtraPrice and MenuItem.Category ='18')

Update [MainDB].[DBO].[Toptions] set F_ItemNo = LEFT(F_ITEMNO,1) + RIGHT(F_ITEMNO,3)

/* Step 12:Set up InstructionLinkGroup Table*/
insert into InstructionLinkGroup(ItemCode,Kind,  SubGroupCode,
 SingleChoice, MinNumberOfChoice, MaxNumberOfChoice)
select Distinct F_ItemNo as ItemCode, F_OptionType - 1 as Kind, '' as SubGroupCode,
0 as SingleChoice, 0 as MinNumberOfChoice, 0 as MaxNumberOfChoice
 from TOptions order by ItemCode
 
insert into InstructionLink (Code, ItemCode,  Kind, 
Qty, Price, Condition, MaximunCharge, IsDefault, ID)
select Distinct F_Code as Code, F_ItemNo as ItemCode, F_OptionType - 1 as Kind, 
1 as Qty, F_ExtraPrice as Price, 1 as Condition, 0 as MaximunCharge, 0 as IsDefault, 1 as ID
 from TOptions order by ItemCode

/* Step 13: Set CATEGORYMENUITEM */

INSERT INTO [MainDB].[dbo].[CATEGORYMENUITEM] (CATEGORY,ITEMCODE) SELECT B.CATEGORY, ITEMCODE FROM MENUITEM A LEFT JOIN CATEGORY B ON A.CATEGORY = B.CODE WHERE ISNULL(B.CATEGORY,'') <> ''


/* Step 14: Set MENUGROUPLINKCATEGORY  */

INSERT INTO  [MainDB].[dbo].[MENUGROUPLINKCATEGORY] (MENUGROUPCODE,CATEGORYCODE) SELECT '00', CODE FROM CATEGORY